# Tutorial: Conceptos básicos de Pytorch
En este tutorial veremos algunos conceptos importantes para poder comenzar a utilizar pytorch para tareas de deep learning.

## Tensores
Un **tensor** es un arreglo multidimensional con elementos del mismo tipo (dtype). En escencia, un tensor de pytorch es muy similar en comportamiento a un array de numpy con algunas diferencias y funcionalidades agregadas.



### Operaciones básicas
Veremos como crear y definir tensores usando pytorch


In [2]:
import torch
import numpy as np

# crear un tensor de rango 0, un escalar, no contiene ejes
simple_tensor = torch.tensor(4)
print(simple_tensor.shape)


torch.Size([])


In [3]:
# un tensor de rango 1 es similar a una lista de valores, tiene un eje
r1_tensor = torch.tensor([2.0,3.0,4.0,5.0])
print(r1_tensor)

tensor([2., 3., 4., 5.])


In [4]:
# un tensor de rango 2 es una matriz
r2_tensor = torch.tensor([[2.0,3.0,4.0,5.0],[1.0,2.0,0.0,1.0]])
print(r2_tensor)

tensor([[2., 3., 4., 5.],
        [1., 2., 0., 1.]])


In [8]:
# un tensor puede tener un numero arbitrario de ejes o dimensiones
rank_3_tensor = torch.tensor([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],], dtype=torch.float32)
                    
print(rank_3_tensor.dtype)

torch.float32


Hay varias formas de visualizar un tensor de más de 2 dimensiones
![tensor](3atensor.png)

In [11]:
# se puede convertir un tensor a un array de numpy de varias maneras:
M = np.array(r2_tensor)
M2 = r2_tensor.numpy()
print(M)
print(type(M2))

[[2. 3. 4. 5.]
 [1. 2. 0. 1.]]
<class 'numpy.ndarray'>


In [12]:
# se pueden realizar operaciones basicas con tensores como adicion, multiplicacion y multiplicacion de matrices
a = torch.tensor([[1, 2],
                 [3, 4]])
b = torch.tensor([[1, 1],
                 [1, 1]]) # tambien se puede usar `tf.ones([2,2])`

print(torch.add(a, b), "\n")
print(torch.multiply(a, b), "\n")
print(torch.matmul(a, b), "\n")
print('numpy:',np.dot(a.numpy(), b.numpy()))
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tensor([[2, 3],
        [4, 5]]) 

tensor([[1, 2],
        [3, 4]]) 

tensor([[3, 3],
        [7, 7]]) 

numpy: [[3 3]
 [7 7]]
tensor([[2, 3],
        [4, 5]]) 

tensor([[1, 2],
        [3, 4]]) 

tensor([[3, 3],
        [7, 7]]) 



In [13]:
# se pueden usar tensores en todo tipo de operaciones adicionales
c = torch.tensor([[4.0, 5.0], [10.0, 1.0]])

# valor maximo
print(torch.max(c))
# indice del valor maximo
print(torch.argmax(c))
# calcular la funcion softmax
print(torch.nn.functional.softmax(c))

tensor(10.)
tensor(2)
tensor([[2.6894e-01, 7.3106e-01],
        [9.9988e-01, 1.2339e-04]])


/var/folders/_1/cy_ykqys6wl_gc741r9fs8mr0000gn/T/ipykernel_18061/1877532574.py:9: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  print(torch.nn.functional.softmax(c))


Se tienen alguas definiciones importantes (similares a numpy):

  - **shape** es el tamaño (numero de elementos) de cada dimension de un tensor.
  - **rank** es el numero de dimensiones del tensor, un escalar tiene rank 0, una matriz rank 2
  - **axis** o **dimension** es una dimensión en particular de un tensor.
  - **size** el numero total de elementos de un tensor, el producto del vector *shape*.
  
Podemos visualizar para un tensor de rank 4


![r4](4atensor.png)


In [14]:
rank_4_tensor = torch.zeros([3, 2, 4, 5])

print("Tipo de cada elemento:", rank_4_tensor.dtype)
print("Numero de dimensiones:", rank_4_tensor.ndim)
print("Shape:", rank_4_tensor.shape)
print("Elementos en el eje 0 del tensor:", rank_4_tensor.shape[0])
print("Elementos en el ultimo eje del tensor:", rank_4_tensor.shape[-1])
print("Numero total de elementos (3*2*4*5): ", rank_4_tensor.numel())

Tipo de cada elemento: torch.float32
Numero de dimensiones: 4
Shape: torch.Size([3, 2, 4, 5])
Elementos en el eje 0 del tensor: 3
Elementos en el ultimo eje del tensor: 5
Numero total de elementos (3*2*4*5):  120


In [16]:
rank_1_tensor = torch.tensor([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
# indexado con un escalar
print(rank_1_tensor.numpy())
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())
# indexado con un slice
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
First: 0
Second: 1
Last: 34
Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]


In [17]:
rank_2_tensor = torch.tensor([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=torch.float16)
print(rank_2_tensor.numpy())
                            
# pasando un entero por cada dimension, arroja un escalar
print(rank_2_tensor[1, 1].numpy())

# Se puede indexar usando combinaciones de escalares y slices
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

[[1. 2.]
 [3. 4.]
 [5. 6.]]
4.0
Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [18]:
print(rank_3_tensor)

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.]],

        [[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]]])


In [20]:
# ejemplo de un tensor de 3 dimensiones
print(rank_3_tensor[:, :, 4].shape)

torch.Size([3, 2])


![3slice](3rslice.png)

In [22]:
# los tensores son mutables
mi_variable = torch.tensor([1, 2, 3])
print(mi_variable + 1)
v = torch.tensor(0.0)
w = v + 1 
print(w)

tensor([2, 3, 4])
tensor(1.)


## Cálculo automático de gradientes

Para poder usar la capacidad de diferenciación automática de pytorch, se necesita recordar todas las operaciones que han ocurrido y el orden de ocurrencia durante el *forward pass*. Luego, durante el *backward pass*, pytorch puede recorrer la lista de operaciones y calcular las gradientes.

### autograd
Pytorch provee la API de **torch.autograd** para la diferenciación automática y poder calcular las gradientes de un grafo de cómputo con respecto a ciertas variables de entrada. Pytorch "recuerda" todas las operaciones ejecutadas dentro un contexto


In [25]:
x = torch.tensor(3.0, requires_grad=True)
# y = x ^ 2
y = x ** 2
# dy = 2x
y.backward()
dy_dx = x.grad
print(y.grad_fn)
print(dy_dx.numpy())

6.0


In [26]:
x = torch.tensor(7.0, requires_grad=True)
y = x + 4
z = y ** 2 - 6

z.backward()

print(x.grad)

tensor(22.)


In [27]:
x = torch.tensor([3.0, 3.0], requires_grad=True)

z = torch.multiply(x, x)

print(z)

z.backward(torch.tensor([1, 1]))
# Find derivative of z with respect to the original input tensor x
print(x.grad)


tensor([9., 9.], grad_fn=<MulBackward0>)
tensor([6., 6.])


Tambien se puede solicitar gradientes de la salida con respecto a valores intermedios calculados durante una "grabación" de un contexto tf.GradientTape

In [ ]:
x = torch.tensor([3.0, 3.0], requires_grad=True)
y = torch.multiply(x, x)
z = torch.multiply(y, y)
z.backward(torch.tensor([1, 1]))
# dz_dx = 2 * y, donde: y = x ^ 2
print(x.grad)


## Regresion lineal en pytorch


In [28]:
from sklearn.datasets import load_diabetes
import random
# X y y ya son arrays de numpy
X, y = load_diabetes(return_X_y=True)

m = X.shape[0]
unos = np.ones((m, 1))
X = np.append(unos, X, axis=1)

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)
print(X.shape, y.shape)

torch.Size([442, 11]) torch.Size([442])
